To use https://jakartaee.github.io/mail-api/[Jakarta Mail], add the following dependency to your application.

dependency:micronaut-email-javamail[groupId="io.micronaut.email"]

In addition, you will need to provide a runtime dependency on an implementation of the Jakarta Mail api. https://eclipse-ee4j.github.io/angus-mail/[Eclipse Angus] is the direct successor to prior versions of JavaMail/JakartaMail.

dependency:angus-mail[groupId="org.eclipse.angus",scope="runtime"]

Micronaut Email can create beans of type api:io.micronaut.email.javamail.sender.MailPropertiesProvider[] and api:io.micronaut.email.javamail.sender.SessionProvider[] from `javamail.properties`.
Configure the Jakarta Mail properties required by your transport, such as SMTP host, port, and TLS settings:

include::{includedir}configurationProperties/io.micronaut.email.javamail.sender.JavaMailConfigurationProperties.adoc[]

Alternatively, provide your own api:io.micronaut.email.javamail.sender.MailPropertiesProvider[] or api:io.micronaut.email.javamail.sender.SessionProvider[] beans when you need complete control over the Jakarta Mail `Session`.

== Authentication via configuration

As an alternative to providing your own api:io.micronaut.email.javamail.sender.SessionProvider[] for authentication, you can configure password based authentication via configuration:

[configuration]
----
javamail:
  authentication:
    username: 'my.username'
    password: 'my.password'
----

include::{includedir}configurationProperties/io.micronaut.email.javamail.sender.authentication.JavaMailAuthenticationConfigurationProperties.adoc[]
